### ISSUE TITLE
Tidb 性能测试

### ISSUE THREAD

**Issue by dulao5** [dulao5/tidb#3]
本 issue 是 [<High Performance TiDB - Lesson 02>](https://www.bilibili.com/video/BV1TD4y1m7AF/) 的作业

作业要求

* 使用 sysbench、go-ycsb 和 go-tpc 分别对 TiDB 进行测试并且产出测试报告

我的做法
* 参考 https://github.com/c4pt0r/tidb-aws-terraform 修改一下配置，并用 terraform 0.13.0 升级一下
  * fork : https://github.com/dulao5/tidb-aws-terraform
* 在 aws 建立一个 tidb 集群
  * 根据 [文档](https://docs.pingcap.com/zh/tidb/stable/hardware-and-software-requirements) 可以先建测试环境规格 的服务器
* 使用 sysbench、go-ycsb 和 go-tpc 分别对 TiDB 进行测试并且产出测试报告

**Comment by dulao5** [comment]
## 测试环境规格

for testing/development
	
  | type  | instanceType  | counts | typeOfSubnet| CPU | Memory | Price/USD/時間 |
  | :-: |:-:| :-:| :-: | :-: | :-: | :-: |
  | bastion | t2.micro   | 1 | public  | 1 | 1 | 0.0116 |
  | tidb    | c4.2xlarge | 3 | priveta | 8 | 15 | 0.398 |
  | tikv    | i3.2xlarge   | 3 | private | 8 | 61 | 0.624 |
  | pd      | m4.xlarge | 3 | private | 4 | 16 | 0.20 |
  | monitor/测试机 | t2.xlarge   | 1 | private | 4 | 16 | 0.1856 |

**Comment by dulao5** [comment]
## tiup 设置

* tidb.yml
<details>
<summary>tidb.yml</summary>

```

# # Global variables are applied to all deployments and used as the default value of
# # the deployments if a specific deployment value is missing.
global:
 user: "ec2-user"
 ssh_port: 22
 deploy_dir: "/tidb-deploy"
 data_dir: "/tidb-data"

# # Monitored variables are applied to all the machines.
monitored:
 node_exporter_port: 9100
 blackbox_exporter_port: 9115

server_configs:
 tidb:
   log.slow-threshold: 300
 tikv:
   readpool.storage.use-unified-pool: false
   readpool.coprocessor.use-unified-pool: true
 pd:
   replication.enable-placement-rules: true
 tiflash:
   logger.level: "info"

pd_servers:
 - host: 10.0.1.234
 - host: 10.0.1.132
 - host: 10.0.1.123

tidb_servers:
 - host: 10.0.1.134
 - host: 10.0.1.115
 - host: 10.0.1.77

tikv_servers:
 - host: 10.0.1.195
 - host: 10.0.1.41
 - host: 10.0.1.85

monitoring_servers:
 - host: 10.0.1.74

grafana_servers:
 - host: 10.0.1.74

```

</details>
